"""
Migra o atletas.db (SQLite) para o Neon (Postgres).

Uso (Windows / PowerShell):
    pip install psycopg2-binary
    $env:DATABASE_URL = "postgresql://USER:SENHA@HOST/neondb?sslmode=require"
    python migrar_para_neon.py

Variáveis:
    DATABASE_URL  -> connection string do Neon (obrigatória)
    SQLITE_PATH   -> caminho do banco local (padrão: atletas.db)

Pode rodar mais de uma vez: tabelas usam IF NOT EXISTS e linhas
já existentes são ignoradas (ON CONFLICT DO NOTHING).
"""
import os
import sqlite3
import sys

import psycopg2
from psycopg2.extras import execute_values

SQLITE_PATH = os.getenv("SQLITE_PATH", "atletas.db")
DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    sys.exit("Defina a variável DATABASE_URL com a connection string do Neon.")
if not os.path.exists(SQLITE_PATH):
    sys.exit(f"Arquivo {SQLITE_PATH} não encontrado.")

SCHEMA = """
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha_hash VARCHAR NOT NULL,
    cidade VARCHAR(80) NOT NULL,
    esporte VARCHAR(40) NOT NULL,
    foto_perfil VARCHAR,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_usuarios_email ON usuarios (email);
CREATE INDEX IF NOT EXISTS ix_usuarios_cidade ON usuarios (cidade);

CREATE TABLE IF NOT EXISTS anuncios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anunciante VARCHAR(100) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    texto VARCHAR(300),
    imagem_url VARCHAR,
    link VARCHAR NOT NULL,
    cidade VARCHAR(80),
    inicio DATE,
    fim DATE,
    ativo BOOLEAN NOT NULL,
    impressoes INTEGER NOT NULL,
    cliques INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_anuncios_cidade ON anuncios (cidade);

CREATE TABLE IF NOT EXISTS turmas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criador_id INTEGER NOT NULL REFERENCES usuarios (id),
    cidade VARCHAR(80) NOT NULL,
    "local" VARCHAR(150) NOT NULL,
    horario TIMESTAMP NOT NULL,
    nivel VARCHAR(20) NOT NULL,
    vagas INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_turmas_cidade ON turmas (cidade);

CREATE TABLE IF NOT EXISTS campeonatos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    divulgador_id INTEGER NOT NULL REFERENCES usuarios (id),
    nome VARCHAR(150) NOT NULL,
    cidade VARCHAR(80) NOT NULL,
    "data" DATE NOT NULL,
    link VARCHAR
);
CREATE INDEX IF NOT EXISTS ix_campeonatos_cidade ON campeonatos (cidade);

CREATE TABLE IF NOT EXISTS corridas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL REFERENCES usuarios (id),
    distancia_km DOUBLE PRECISION NOT NULL,
    tempo_seg INTEGER NOT NULL,
    "data" DATE NOT NULL,
    legenda VARCHAR,
    comprovante_url VARCHAR,
    criado_em TIMESTAMP NOT NULL,
    trajeto TEXT,
    origem VARCHAR(10) NOT NULL DEFAULT 'manual'
);
CREATE INDEX IF NOT EXISTS ix_corridas_usuario_id ON corridas (usuario_id);
CREATE INDEX IF NOT EXISTS ix_corridas_distancia_km ON corridas (distancia_km);

CREATE TABLE IF NOT EXISTS turma_membros (
    turma_id INTEGER NOT NULL REFERENCES turmas (id),
    usuario_id INTEGER NOT NULL REFERENCES usuarios (id),
    PRIMARY KEY (turma_id, usuario_id)
);

CREATE TABLE IF NOT EXISTS curtidas (
    usuario_id INTEGER NOT NULL REFERENCES usuarios (id),
    corrida_id INTEGER NOT NULL REFERENCES corridas (id),
    PRIMARY KEY (usuario_id, corrida_id)
);

CREATE TABLE IF NOT EXISTS fotos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corrida_id INTEGER NOT NULL REFERENCES corridas (id),
    url VARCHAR NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_fotos_corrida_id ON fotos (corrida_id);
"""

# (tabela, colunas, colunas booleanas, tem coluna id)
# A ordem respeita as chaves estrangeiras.
TABLES = [
    ("usuarios",
     ["id", "nome", "email", "senha_hash", "cidade", "esporte", "foto_perfil", "is_admin", "ativo"],
     {"is_admin", "ativo"}, True),
    ("anuncios",
     ["id", "anunciante", "titulo", "texto", "imagem_url", "link", "cidade", "inicio", "fim",
      "ativo", "impressoes", "cliques", "criado_em"],
     {"ativo"}, True),
    ("turmas",
     ["id", "criador_id", "cidade", "local", "horario", "nivel", "vagas"],
     set(), True),
    ("campeonatos",
     ["id", "divulgador_id", "nome", "cidade", "data", "link"],
     set(), True),
    ("corridas",
     ["id", "usuario_id", "distancia_km", "tempo_seg", "data", "legenda", "comprovante_url",
      "criado_em", "trajeto", "origem"],
     set(), True),
    ("turma_membros", ["turma_id", "usuario_id"], set(), False),
    ("curtidas", ["usuario_id", "corrida_id"], set(), False),
    ("fotos", ["id", "corrida_id", "url"], set(), True),
]


def main():
    lite = sqlite3.connect(SQLITE_PATH)
    pg = psycopg2.connect(DATABASE_URL)
    cur = pg.cursor()

    print("Criando tabelas no Neon...")
    cur.execute(SCHEMA)
    pg.commit()

    existentes = {r[0] for r in lite.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    resumo = []

    for tabela, colunas, booleanas, tem_id in TABLES:
        if tabela not in existentes:
            print(f"  {tabela}: não existe no SQLite, pulando")
            continue

        cols_sql = ", ".join(f'"{c}"' for c in colunas)
        rows = lite.execute(f"SELECT {cols_sql} FROM {tabela}").fetchall()

        idx_bool = [i for i, c in enumerate(colunas) if c in booleanas]
        convertidas = []
        for r in rows:
            r = list(r)
            for i in idx_bool:
                if r[i] is not None:
                    r[i] = bool(r[i])
            convertidas.append(tuple(r))

        if convertidas:
            execute_values(
                cur,
                f'INSERT INTO {tabela} ({cols_sql}) VALUES %s ON CONFLICT DO NOTHING',
                convertidas,
            )

        if tem_id:
            # Ajusta o contador de IDs para os próximos registros não colidirem.
            cur.execute(
                f"SELECT setval(pg_get_serial_sequence('public.{tabela}', 'id'), "
                f"COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM {tabela}"
            )

        pg.commit()
        cur.execute(f"SELECT COUNT(*) FROM {tabela}")
        resumo.append((tabela, len(rows), cur.fetchone()[0]))

    print("\nConferência (SQLite -> Neon):")
    for tabela, n_lite, n_pg in resumo:
        status = "OK" if n_pg >= n_lite else "VERIFICAR"
        print(f"  {tabela:15} {n_lite:6} -> {n_pg:6}  {status}")

    cur.close()
    pg.close()
    lite.close()
    print("\nPronto. Agora aponte o backend para o DATABASE_URL do Neon.")


if __name__ == "__main__":
    main()